export const getLabelsLayers = (source, t, lang) => {
  return [
    {
      id: 'physical_line_waterway_label',
      type: 'symbol',
      source: source,
      'source-layer': 'physical_line',
      minzoom: 13,
      filter: ['all', ['in', 'pmap:kind', 'river', 'stream']],
      layout: {
        'symbol-placement': 'line',
        'text-font': ['Noto Sans Regular'],
        //"text-field": ["get", "name"],
        'text-field': ['get', `{name:${lang}}`],
        'text-size': 12,
        'text-letter-spacing': 0.3,
      },
      paint: {
        'text-color': t.waterway_label,
      },
    },
    {
      id: 'physical_point_peak',
      type: 'symbol',
      source: source,
      'source-layer': 'physical_point',
      filter: ['any', ['==', 'pmap:kind', 'peak']],
      layout: {
        'text-font': ['Noto Sans Italic'],
        //"text-field": ["get", "name"],
        'text-field': ['get', `{name:${lang}}`],
        'text-size': ['interpolate', ['linear'], ['zoom'], 10, 8, 16, 12],
        'text-letter-spacing': 0.1,
        'text-max-width': 9,
      },
      paint: {
        'text-color': t.peak_label,
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'roads_labels_minor',
      type: 'symbol',
      source: source,
      'source-layer': 'roads',
      minzoom: 15,
      filter: ['any', ['in', 'pmap:kind', 'minor_road', 'other', 'path']],
      layout: {
        'symbol-sort-key': ['get', 'pmap:min_zoom'],
        'symbol-placement': 'line',
        'text-font': ['Noto Sans Regular'],
        //"text-field": ["get", "name"],
        'text-field': ['get', `{name:${lang}}`],
        'text-size': 12,
      },
      paint: {
        'text-color': t.roads_label_minor,
        'text-halo-color': t.roads_label_minor_halo,
        'text-halo-width': 2,
      },
    },
    // {
    //   id: "pois_high_zooms",
    //   type: "symbol",
    //   source: source,
    //   minzoom: 15,
    //   "source-layer": "pois",
    //   "filter": ["any", [">=", ["get", "pmap:min_zoom"], 13]],
    //   layout: {
    //     "symbol-sort-key": ["get", "pmap:min_zoom"],
    //     "text-font": ["Noto Sans Regular"],
    //     "text-field": ["get", "name"],
    //     "text-size": 11,
    //     "text-max-width": 9,
    //     "icon-padding": ["interpolate", ["linear"],
    //       ["zoom"], 0, 2, 14, 2, 16, 20, 17, 2, 22, 2
    //     ],
    //   },
    //   paint: {
    //     "text-color": t.subplace_label,
    //     "text-halo-color": t.subplace_label_halo,
    //     "text-halo-width": 1.5,
    //   },
    // },
    {
      id: 'physical_point_ocean',
      type: 'symbol',
      source: source,
      'source-layer': 'physical_point',
      filter: [
        'any',
        [
          'in',
          'pmap:kind',
          'sea',
          'ocean',
          'lake',
          'water',
          'bay',
          'strait',
          'fjord',
        ],
      ],
      layout: {
        'text-font': ['Noto Sans Medium'],
        //"text-field": ["get", "name"],
        'text-field': ['get', `{name:${lang}}`],
        'text-size': ['interpolate', ['linear'], ['zoom'], 3, 10, 10, 12],
        'text-letter-spacing': 0.1,
        'text-max-width': 9,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': t.ocean_label,
      },
    },
    {
      id: 'physical_point_lakes',
      type: 'symbol',
      source: source,
      'source-layer': 'physical_point',
      filter: ['any', ['in', 'pmap:kind', 'lake', 'water']],
      layout: {
        'text-font': ['Noto Sans Medium'],
        //"text-field": ["get", "name"],
        'text-field': ['get', `{name:${lang}}`],
        'text-size': ['interpolate', ['linear'], ['zoom'], 3, 0, 6, 12, 10, 12],
        'text-letter-spacing': 0.1,
        'text-max-width': 9,
      },
      paint: {
        'text-color': t.ocean_label,
      },
    },
    {
      id: 'roads_labels_major',
      type: 'symbol',
      source: source,
      'source-layer': 'roads',
      minzoom: 11,
      filter: [
        'any',
        ['in', 'pmap:kind', 'highway', 'major_road', 'medium_road'],
      ],
      layout: {
        'symbol-sort-key': ['get', 'pmap:min_zoom'],
        'symbol-placement': 'line',
        'text-font': ['Noto Sans Regular'],
        //"text-field": ["get", "name"],
        'text-field': ['get', `{name:${lang}}`],
        'text-size': 12,
      },
      paint: {
        'text-color': t.roads_label_major,
        'text-halo-color': t.roads_label_major_halo,
        'text-halo-width': 2,
      },
    },
    {
      id: 'places_subplace',
      type: 'symbol',
      source: source,
      'source-layer': 'places',
      filter: ['==', 'pmap:kind', 'neighbourhood'],
      layout: {
        'symbol-sort-key': ['get', 'pmap:min_zoom'],
        //"text-field": "{name}",
        'text-field': `{name:${lang}}`,
        'text-font': ['Noto Sans Regular'],
        'text-max-width': 7,
        'text-letter-spacing': 0.1,
        'text-padding': [
          'interpolate',
          ['linear'],
          ['zoom'],
          5,
          2,
          8,
          4,
          12,
          18,
          15,
          20,
        ],
        'text-size': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          11,
          8,
          14,
          14,
          18,
          14,
        ],
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': t.subplace_label,
        'text-halo-color': t.subplace_label_halo,
        'text-halo-width': 2.0,
      },
    },
    {
      id: 'pois_important',
      type: 'symbol',
      source: source,
      'source-layer': 'pois',
      filter: ['any', ['<', ['get', 'pmap:min_zoom'], 13]],
      layout: {
        'symbol-sort-key': ['get', 'pmap:min_zoom'],
        'text-font': ['Noto Sans Regular'],
        //"text-field": ["get", "name"],
        'text-field': ['get', `{name:${lang}}`],
        'text-size': 11,
        'text-max-width': 9,
        'icon-padding': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          2,
          14,
          2,
          16,
          20,
          17,
          2,
          22,
          2,
        ],
      },
      paint: {
        'text-color': t.subplace_label,
        'text-halo-color': t.subplace_label_halo,
        'text-halo-width': 1.5,
      },
    },
    /*{
    id: "places_locality_circle",
    type: "circle",
    source: source,
    "source-layer": "places",
    filter: ["==", "pmap:kind", "locality"],
    paint: {
      "circle-radius": 2,
      "circle-stroke-width": 1.5,
      "circle-stroke-color": t.city_circle_stroke,
      "circle-color": t.city_circle,
      "circle-translate": [-6, 0],
    },
    maxzoom: 8,
  },*/
    {
      id: 'places_locality',
      type: 'symbol',
      source: source,
      'source-layer': 'places',
      filter: ['==', 'pmap:kind', 'locality'],
      layout: {
        //"text-field": `{name:${lang}}`,
        //"text-field": "{name}",
        'text-field': ['coalesce', ['get', `name:${lang}`], ['get', 'name']],
        'text-font': [
          'case',
          ['<=', ['get', 'pmap:min_zoom'], 5],
          ['literal', ['Noto Sans Medium']],
          ['literal', ['Noto Sans Regular']],
        ],
        'text-padding': [
          'interpolate',
          ['linear'],
          ['zoom'],
          5,
          3,
          8,
          7,
          12,
          11,
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          2,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 13],
            8,
            ['>=', ['get', 'pmap:population_rank'], 13],
            11,
            0,
          ],
          4,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 13],
            9,
            ['>=', ['get', 'pmap:population_rank'], 13],
            13,
            0,
          ],
          6,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 12],
            10,
            ['>=', ['get', 'pmap:population_rank'], 12],
            15,
            0,
          ],
          8,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 11],
            10,
            ['>=', ['get', 'pmap:population_rank'], 11],
            15,
            0,
          ],
          10,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 9],
            12,
            ['>=', ['get', 'pmap:population_rank'], 9],
            17,
            0,
          ],
          15,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 8],
            12,
            ['>=', ['get', 'pmap:population_rank'], 8],
            17,
            0,
          ],
        ],
        'icon-padding': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          2,
          8,
          4,
          10,
          8,
          12,
          6,
          22,
          2,
        ],
        'text-anchor': ['step', ['zoom'], 'left', 8, 'center'],
        'text-radial-offset': 0.2,
      },
      paint: {
        'text-color': t.city_label,
        'text-halo-color': t.city_label_halo,
        'text-halo-width': 1,
      },
    },
    {
      id: 'places_region',
      type: 'symbol',
      source: source,
      'source-layer': 'places',
      filter: ['==', 'pmap:kind', 'region'],
      layout: {
        'symbol-sort-key': ['get', 'pmap:min_zoom'],
        'text-field': [
          'step',
          ['zoom'],
          ['get', 'name:short'],
          6,
          ['get', 'name'],
        ],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 3, 11, 7, 16],
        'text-radial-offset': 0.2,
        'text-anchor': 'center',
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': t.state_label,
        'text-halo-color': t.state_label_halo,
        'text-halo-width': 2,
      },
    },
    {
      id: 'places_country',
      type: 'symbol',
      source: source,
      'source-layer': 'places',
      filter: ['==', 'pmap:kind', 'country'],
      layout: {
        'symbol-sort-key': ['get', 'pmap:min_zoom'],
        //"text-field": "{name}",
        'text-field': `{name:${lang}}`,
        'text-font': ['Noto Sans Medium'],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          2,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 10],
            8,
            ['>=', ['get', 'pmap:population_rank'], 10],
            12,
            0,
          ],
          6,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 8],
            10,
            ['>=', ['get', 'pmap:population_rank'], 8],
            12,
            0,
          ],
          8,
          [
            'case',
            ['<', ['get', 'pmap:population_rank'], 7],
            10,
            ['>=', ['get', 'pmap:population_rank'], 7],
            12,
            0,
          ],
        ],
        'icon-padding': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          2,
          14,
          2,
          16,
          20,
          17,
          2,
          22,
          2,
        ],
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': t.country_label,
      },
    },
  ]
}
